[General]
importPaths=/usr/lib/python3.14/site-packages/PySide6/Qt/qml:/usr/bin:/usr/lib/qt6/qml

# python -c "import PySide6; import os; print(os.path.join(os.path.dirname(PySide6.__file__), 'Qt', 'qml'))"